name: Testando API do ViaCep

on:
  push:
    branches:
      - main

jobs:
  test_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar curl
      run: sudo apt-get install -y curl

    - name: Veriicar resposta da API de CEP
      run: |
        resposta=$(curl -s "https://viacep.com.br/ws/08275090/json/")
        if echo "$resposta" | grep -q '"logradouro"'; then
          echo "Validação bem-sucedida!"
        else
          echo "Validação falhou!"
          exit 1
        fi